### ISSUE TITLE
OSX, add the binary directory to the PATH and restart the terminal?

### ISSUE THREAD

**Issue by albinotonnina** [stream-deck-for-node/cli#4]
Hello, 
issues on MAC, yarn having `env: node\r: No such file or directory`  https://stackoverflow.com/a/30349952

With npm looks better

now stream-deck create:

![image](https://user-images.githubusercontent.com/37283/222587628-888b91a0-769c-4af2-9a3b-d79d15772090.png)

tested couple paths with no success. Any documentation around this error?

Thank you

**Comment by fcannizzaro** [comment]
I think this was fixed by 9314e84835cfb78aae4e83307cc7e0ff6261887e
